//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedimientos_Citas
    {
        public int cita_ID { get; set; }
        public int procedimiento_ID { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Citas Citas { get; set; }
        public virtual Procedimientos Procedimientos { get; set; }
    }
}
